fix(performance_v3): fix getState error in renderStatistics
- Use metrics.framesRendered instead of this.getState('framesRendered')
- PerformanceChartRenderer doesn't have access to state functions
- Fixes runtime error: this.getState is not a function